### ISSUE TITLE
Consider other options for css processing

### ISSUE THREAD

**Issue by phated** [gulp-sourcemaps/identity-map#1]
As per @nmccready in gulp-sourcemaps/gulp-sourcemaps/issues/290

> I just wanted to make a note here that we should possibly consider something other than `css` for doing our css mapping. It has numerous problems and does not seem to be very active. It is responsible for many of the closed bugs that relate to sass and css mapping problems.

Maybe we can use PostCSS?

**Comment by nmccready** [comment]
I am looking into this.
