### ISSUE TITLE
JS hashbang error

### ISSUE THREAD

**Issue by Delagen** [gulp-sourcemaps/identity-map#3]
From gulp-sourcemaps plugin
```
.pipe(sourcemaps.identityMap());
```
crash when JS contains hashBang first line

I think need `allowHashBang` option enabled or way to pass it from gulp plugin
```
var tokenizer = acorn.tokenizer(fileContent, { allowHashBang: true, locations: true });
```

**Comment by phated** [comment]
@Delagen interesting.  I thought hashbang was inside a comment, so it seems weird that they would crash on it.

Mind sending a PR with tests?

**Comment by Delagen** [comment]
I am not sure if expose it as option, or make it default? @phated how about your opinion?

**Comment by phated** [comment]
@Delagen It looks like [the code](https://github.com/ternjs/acorn/blob/9afa6c75aae64a2458316ffb54f1ee2422fdaeb7/src/state.js#L86) is very specific (and not intrusive), so turning it on always seems fine.  I don't think it needs to be paired with the `locations` option though.

**Comment by Delagen** [comment]
Created PR #4
